# Weeks 7 & 8 Exercise 

Author: Rosie Navarro

Date: October 23 2026

The purpose of this week's assignment is to complete 8 Data preparation from chapter 7, 8, 10, and 11. The assignment will be broken down into chapters. 

The first part of the assinment is to load the data that is going to be used and make sure that it was loaded properly. For this assingment the "So Much Candy Data, Seriously" was used.

In [1]:
import pandas as pd

In [2]:
candy = pd.read_csv("candyhierarchy2017.csv", encoding="latin1")

candy.head(15)

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,90272829,NaN,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,NaN,Raisins can go to hell,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"
5,90272852,No,Male,NaN,NaN,NaN,JOY,DESPAIR,JOY,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,"(75, 23)"
6,90272853,No,Male,53,usa,Colorado,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,90272854,No,Male,33,canada,ontario,JOY,DESPAIR,JOY,DESPAIR,...,when the little kids get the big chocolate bar...,"first person to give out cans of beer, wins",Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(55, 5)"
8,90272858,No,Male,40,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,NaN,NaN,Blue and black,NaN,Sunday,NaN,1.0,NaN,NaN,"(76, 24)"
9,90272859,No,Female,53,Us,Wa,MEH,DESPAIR,JOY,MEH,...,NaN,NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(70, 28)"
10,90272861,Yes,Male,43,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,90272865,No,Male,56,Canada,Quebec,JOY,MEH,JOY,MEH,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(73, 24)"
12,90272866,No,Male,64,US,NY,MEH,MEH,JOY,MEH,...,NaN,NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(77, 24)"
13,90272867,Yes,Male,43,Murica,California,JOY,DESPAIR,JOY,MEH,...,Rain on halloween and nuclear war. I thought w...,Anything hershey should automatically get rank...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,NaN
14,90272868,No,Female,37,Canada,Ontario,MEH,JOY,JOY,MEH,...,Coupons,NaN,Blue and black,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 25)"

The first 15 rows were loaded, the main thing that can be seen is that there is a good amount of data that has missing values. These varibles can be further examined using the info function.

In [3]:
candy.info()

<class 'pandas.DataFrame'>
RangeIndex: 2460 entries, 0 to 2459
Columns: 120 entries, Internal ID to Click Coordinates (x, y)
dtypes: float64(4), int64(1), str(115)
memory usage: 2.3 MB

One interesting thing about this dataset is that there are 120 columns/varibles. By looking at the questions that were asked, you can see that there are a list of items that can be ranked from joy, meh, or despair (this is from question 6). 

To confirm that is the main issues, all of the columns names can she shown using tolist.

Question 6 issue will be resolved later on in the assignment. 

## Chapter 7: 
For this part of the assignment, filtering missing data and removing duplicates will be the main focus.

In [4]:
candy.isna().sum().sort_values(ascending=False)

Unnamed: 113                        2451
Q12: MEDIA [Yahoo]                  2393
Q12: MEDIA [Daily Dish]             2375
Q12: MEDIA [ESPN]                   2361
Q9: OTHER COMMENTS                  2074
                                    ...
Q5: STATE, PROVINCE, COUNTY, ETC     100
Q3: AGE                               84
Q4: COUNTRY                           64
Q2: GENDER                            41
Internal ID                            0
Length: 120, dtype: int64

unnamed 113 has a total of 2451 missing values out of the 2460 rows. Before anything can be done, we first have to check why there are some values here. Dropna filters the missing values, only the values that are present will be shown.

In [5]:
candy["Unnamed: 113"].dropna()

229     dress (https://survey.ubc.ca/media/assets/user...
268     dress (https://survey.ubc.ca/media/assets/user...
603     dress (https://survey.ubc.ca/media/assets/user...
1055    dress (https://survey.ubc.ca/media/assets/user...
1156    dress (https://survey.ubc.ca/media/assets/user...
1506    dress (https://survey.ubc.ca/media/assets/user...
1600    dress (https://survey.ubc.ca/media/assets/user...
2215    dress (https://survey.ubc.ca/media/assets/user...
2302    dress (https://survey.ubc.ca/media/assets/user...
Name: Unnamed: 113, dtype: str

From Unnamed: 113 there is a total of 9 values that are present, they do not provide much information. Additionally when looking at the survey, there is not question that makes sense, other then a link that was added. It would make senst to get rid of this column.

In [6]:
candy1 = candy.drop(columns=["Unnamed: 113"])

In [7]:
candy1.head(10)

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q7: JOY OTHER,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,Mounds,NaN,Bottom line is Twix is really the only candy w...,White and gold,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,90272829,NaN,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,"Reese's crispy crunchy bars, 5th avenue bars, ...",NaN,Raisins can go to hell,White and gold,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,NaN,NaN,NaN,White and gold,Friday,NaN,1.0,NaN,NaN,"(70, 10)"
5,90272852,No,Male,NaN,NaN,NaN,JOY,DESPAIR,JOY,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,"(75, 23)"
6,90272853,No,Male,53,usa,Colorado,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,90272854,No,Male,33,canada,ontario,JOY,DESPAIR,JOY,DESPAIR,...,using my elbows to get in front of the little ...,when the little kids get the big chocolate bar...,"first person to give out cans of beer, wins",Blue and black,Friday,NaN,1.0,NaN,NaN,"(55, 5)"
8,90272858,No,Male,40,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,NaN,NaN,NaN,Blue and black,Sunday,NaN,1.0,NaN,NaN,"(76, 24)"
9,90272859,No,Female,53,Us,Wa,MEH,DESPAIR,JOY,MEH,...,Peanut butter m&ms,NaN,NaN,White and gold,Sunday,NaN,1.0,NaN,NaN,"(70, 28)"

Question 12 and 9 also contain a decent amount of null values (2000+). These can also go through the filter method. One thing that cannot be done is dropna(), if that is done, there would be no values in the dataset.

Another thing that will be done in this section is getting rid of duplicates, or checking to see if there are any duplicates in the dataset.

In [8]:
candy1.duplicated().sum()

np.int64(0)

There are no duplicates in the dataset, therefore none of the values need to be deleted. 

## Ch 8: 

The first step in this chapter is to convert the dataset from wide to a long format. The format will only show the candy that is being rated, the candy, and the respondent number (which should be unique).

In [9]:
q6 = candy1.filter(regex=r"^Q6\s*\|").columns

candy_long = candy1[q6].reset_index().melt(
    id_vars="index", 
    var_name="Candy", 
    value_name="Rating")

candy_long = candy_long.rename(columns={"index":"Respondent"})

In [10]:
candy_long.head()

   Respondent               Candy Rating
0           0  Q6 | 100 Grand Bar    NaN
1           1  Q6 | 100 Grand Bar    MEH
2           2  Q6 | 100 Grand Bar    NaN
3           3  Q6 | 100 Grand Bar    MEH
4           4  Q6 | 100 Grand Bar    JOY

The following only shows the Candy rating for 100 Grand Bar for the first 15 respondents. This is also known as hierachical indexing, it has two levels candy and rating.

In [11]:
candy_in = candy_long.set_index(["Candy", "Rating"])

candy_in.head(15)

                           Respondent
Candy              Rating
Q6 | 100 Grand Bar nan              0
                   MEH              1
                   nan              2
                   MEH              3
                   JOY              4
                   JOY              5
                   nan              6
                   JOY              7
                   JOY              8
                   MEH              9
                   nan             10
                   JOY             11
                   MEH             12
                   JOY             13
                   MEH             14

Any type of candy and its rating can be found, for example the twix ratings:

In [16]:
candy_in.loc["Q6 | Twix"]

         Respondent
Rating
NaN               0
JOY               1
NaN               2
JOY               3
JOY               4
...             ...
JOY            2455
JOY            2456
MEH            2457
NaN            2458
DESPAIR        2459

[2460 rows x 1 columns]

The next part of chapter 8 is to create a pivot table.

In [36]:
candy_pivot = candy_long.pivot_table(
    index="Candy", 
    columns="Rating",
    aggfunc="size", 
    fill_value=0)

candy_pivot.head(20)

Rating                                              DESPAIR   JOY  MEH
Candy
Q6 | 100 Grand Bar                                       85   873  755
Q6 | Abstained from M&M'ing.                            693   218  607
Q6 | Anonymous brown globs that come in black a...     1089   176  461
Q6 | Any full-sized candy bar                            17  1559  212
Q6 | Black Jacks                                        793    92  617
Q6 | Blue M&M's                                         120  1018  595
Q6 | Bonkers (the board game)                           546   193  715
Q6 | Bonkers (the candy)                                495   116  857
Q6 | Bottle Caps                                        560   465  670
Q6 | Box'o'Raisins                                     1179   117  476
Q6 | Broken glow stick                                 1625    24  105
Q6 | Butterfinger                                       141  1177  460
Q6 | Cadbury Creme Eggs                                 395   820  562
Q6 | Candy Corn                                         743   478  561
Q6 | Candy that is clearly just the stuff given...     1325    39  405
Q6 | Caramellos                                         163   953  592
Q6 | Cash, or other forms of legal tender                65  1439  276
Q6 | Chardonnay                                         317  1040  360
Q6 | Chick-o-Sticks (we donÕt know what that is)        644   299  571
Q6 | Chiclets                                           761   244  744

The information from the pivot table is easier to understand. It has a list of candy and the number of times it was rated despair, meh, or joy. 

## Ch. 10: 
This chapter will focus on grouping with index levels, and doing split, apply, combine. 

The first part we will group by index level. The idea is to see how many candies were ranked dispair, joy, or meh. The first step is to make sure that there are two levels, rating and candy. After that is done it can be grouped by index level (rating).

In [49]:
candy_summary = candy1[q6].apply(
    lambda col: col.value_counts()).fillna(0).astype(int)

In [50]:
candy_summary = candy_summary.stack()

candy_summary.index.names=["Candy", "Rating"]

candy_total = candy_summary.groupby(level="Candy").sum()
candy_total

Candy
DESPAIR    58254
JOY        64206
MEH        53095
dtype: int64

Most are in the joy category (64206) and meh has the least (53095). 

The next thing that will be done in chapter 10 is split, apply, combine. The goal is to see how many times each candy has joy, meh, or despair. In other words, this is the same thing that we have done previously, but it SPLITs the candy by columns, APPLYs the percentage of joy, despair, and meh for each candy, and COMBINES the results in a dataframe.

In [53]:
rating = candy1[q6].apply(
    lambda col: col.value_counts(normalize=True) * 100)
# multiplied by 100 for percentage

rating

,Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),Q6 | Bonkers (the board game),Q6 | Bottle Caps,Q6 | Box'o'Raisins,Q6 | Broken glow stick,Q6 | Butterfinger,...,Q6 | Three Musketeers,Q6 | Tolberone something or other,Q6 | Trail Mix,Q6 | Twix,"Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein",Q6 | Vicodin,Q6 | Whatchamacallit Bars,Q6 | White Bread,Q6 | Whole Wheat anything,Q6 | York Peppermint Patties
DESPAIR,4.962055,63.093859,0.950783,52.796272,33.719346,37.551582,33.038348,66.534989,92.645382,7.930259,...,10.045662,4.789054,47.716895,4.011299,68.705036,43.267504,17.593158,85.437463,75.248103,13.219373
JOY,50.963222,10.196987,87.192394,6.125166,7.901907,13.273728,27.433628,6.602709,1.368301,66.197975,...,60.388128,75.256556,13.013699,79.830508,13.968825,42.309994,51.313378,2.583676,6.830123,62.962963
MEH,44.074723,26.709154,11.856823,41.078562,58.378747,49.174691,39.528024,26.862302,5.986317,25.871766,...,29.566210,19.954390,39.269406,16.158192,17.326139,14.422501,31.093464,11.978861,17.921775,23.817664

All of the candies have different results. There are some that were rated more joy then meh, while other were more despair thant the other options. 

## Ch. 11:
For the last part of the assignment, this chapter will focus on dates. Since this date does not contain any type of dates, the first step would be to generate a date range.

In [60]:
dates = pd.date_range(
    start="2016-01-25", 
    periods=len(candy1), 
    freq="D")
dates

DatetimeIndex(['2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
               '2016-01-29', '2016-01-30', '2016-01-31', '2016-02-01',
               '2016-02-02', '2016-02-03',
               ...
               '2022-10-10', '2022-10-11', '2022-10-12', '2022-10-13',
               '2022-10-14', '2022-10-15', '2022-10-16', '2022-10-17',
               '2022-10-18', '2022-10-19'],
              dtype='datetime64[us]', length=2460, freq='D')

Once all of the dates have been generated they can be added to the dataset.

In [61]:
candy1["Date_entry"] = dates
candy1.head(10)

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)",Date_entry
0,90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-01-25
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,NaN,Bottom line is Twix is really the only candy w...,White and gold,Sunday,NaN,1.0,NaN,NaN,"(84, 25)",2016-01-26
2,90272829,NaN,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-01-27
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,NaN,Raisins can go to hell,White and gold,Sunday,NaN,1.0,NaN,NaN,"(75, 23)",2016-01-28
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,NaN,NaN,White and gold,Friday,NaN,1.0,NaN,NaN,"(70, 10)",2016-01-29
5,90272852,No,Male,NaN,NaN,NaN,JOY,DESPAIR,JOY,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,"(75, 23)",2016-01-30
6,90272853,No,Male,53,usa,Colorado,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-01-31
7,90272854,No,Male,33,canada,ontario,JOY,DESPAIR,JOY,DESPAIR,...,when the little kids get the big chocolate bar...,"first person to give out cans of beer, wins",Blue and black,Friday,NaN,1.0,NaN,NaN,"(55, 5)",2016-02-01
8,90272858,No,Male,40,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,NaN,NaN,Blue and black,Sunday,NaN,1.0,NaN,NaN,"(76, 24)",2016-02-02
9,90272859,No,Female,53,Us,Wa,MEH,DESPAIR,JOY,MEH,...,NaN,NaN,White and gold,Sunday,NaN,1.0,NaN,NaN,"(70, 28)",2016-02-03

Now that there is a date for each respondent in the dataset, the dates can now be converted to string, same formate but it goes by month, day, then year.

In [65]:
candy1["Date_String"] = candy1["Date_entry"].dt.strftime("%m-%d-%Y")

candy1.head(10)

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q9: OTHER COMMENTS,Q10: DRESS,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)",Date_entry,Date_String
0,90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-01-25,01-25-2016
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,Bottom line is Twix is really the only candy w...,White and gold,Sunday,NaN,1.0,NaN,NaN,"(84, 25)",2016-01-26,01-26-2016
2,90272829,NaN,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-01-27,01-27-2016
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,Raisins can go to hell,White and gold,Sunday,NaN,1.0,NaN,NaN,"(75, 23)",2016-01-28,01-28-2016
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,NaN,White and gold,Friday,NaN,1.0,NaN,NaN,"(70, 10)",2016-01-29,01-29-2016
5,90272852,No,Male,NaN,NaN,NaN,JOY,DESPAIR,JOY,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,"(75, 23)",2016-01-30,01-30-2016
6,90272853,No,Male,53,usa,Colorado,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-01-31,01-31-2016
7,90272854,No,Male,33,canada,ontario,JOY,DESPAIR,JOY,DESPAIR,...,"first person to give out cans of beer, wins",Blue and black,Friday,NaN,1.0,NaN,NaN,"(55, 5)",2016-02-01,02-01-2016
8,90272858,No,Male,40,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,NaN,Blue and black,Sunday,NaN,1.0,NaN,NaN,"(76, 24)",2016-02-02,02-02-2016
9,90272859,No,Female,53,Us,Wa,MEH,DESPAIR,JOY,MEH,...,NaN,White and gold,Sunday,NaN,1.0,NaN,NaN,"(70, 28)",2016-02-03,02-03-2016

Now convert it back to datetime.

In [68]:
candy1["Date Converted"] = pd.to_datetime(
    candy1["Date_String"])

candy1.head()

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q10: DRESS,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)",Date_entry,Date_String,Date Converted
0,90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-01-25,01-25-2016,2016-01-25
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,White and gold,Sunday,NaN,1.0,NaN,NaN,"(84, 25)",2016-01-26,01-26-2016,2016-01-26
2,90272829,NaN,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-01-27,01-27-2016,2016-01-27
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,White and gold,Sunday,NaN,1.0,NaN,NaN,"(75, 23)",2016-01-28,01-28-2016,2016-01-28
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,White and gold,Friday,NaN,1.0,NaN,NaN,"(70, 10)",2016-01-29,01-29-2016,2016-01-29

The dataset now contains all the the date related columns that way the changes can easily be seen.